### ISSUE TITLE
Issue with ConfigMap when creating ChaosToolkitExperiment

### ISSUE THREAD

**Issue by dmartin35** [chaostoolkit-incubator/kubernetes-crd#18]
```
[2020-03-19 16:03:07,467] kopf.objects         [ERROR   ] [chaostoolkit-crd/my-chaos-exp] Handler 'create_chaos_experiment' failed with an exception. Will retry.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/kopf/reactor/handling.py", line 291, in execute_handler_once
    lifecycle=lifecycle,  # just a default for the sub-handlers, not used directly.
  File "/usr/local/lib/python3.7/site-packages/kopf/reactor/handling.py", line 380, in invoke_handler
    **kwargs,
  File "/usr/local/lib/python3.7/site-packages/kopf/reactor/invocation.py", line 117, in invoke
    result = await fn(*args, **kwargs)  # type: ignore
  File "controller.py", line 67, in create_chaos_experiment
    kopf.adopt(cm_tpl, owner=body)
  File "/usr/local/lib/python3.7/site-packages/kopf/toolkits/hierarchies.py", line 139, in adopt
    append_owner_reference(objs, owner=real_owner)
  File "/usr/local/lib/python3.7/site-packages/kopf/toolkits/hierarchies.py", line 28, in append_owner_reference
    refs = obj.setdefault('metadata', {}).setdefault('ownerReferences', [])
AttributeError: 'V1ConfigMap' object has no attribute 'setdefault'
```

**Comment by dmartin35** [comment]
**workaround**:
wait for a couple of seconds that kubernetes retries to launch it, and the second time it works fine

are all resources (ie config map) created when the CRD tries to create  the experiment pod ?
